### ISSUE TITLE
issue with firewall when two servers defined

### ISSUE THREAD

**Issue by peceka** [voxpupuli/puppet-zabbix#199]
Hi,

in my infrastructure all zbx-agnts are monitored by zbx-proxies. but when i want to set executing command on trigger i need to add beside zbx-proxy zbx-server too. so i need to define:
zabbix::agent::server: 'zbx-prxy.host, zbx-srv.host'
/etc/zabbix/zabbix-agentd.conf is build correctly but when using firewall i've got:
Error: Failed to apply catalog: Parameter source failed on Firewall[150 zabbix-agent]: host_to_ip failed for zbx-prxy.host, zbx-srv.host, exception no address for zbx-prxy.host, zbx-srv.host at /etc/puppet/environments/prod/modules/zabbix/manifests/agent.pp:355

creating array in yaml resolves firewall problem, but create problem with zabbix-agentd.conf:
Server=["zbx-prxy.host", ", zbx-srv.host"]
which of course doesn't work.

any ideas how to do this? :)

regards,
p.

**Comment by dj-wasabi** [comment]
Hi @peceka 

At the moment, no. I'll try to find out a solution for this.
