### ISSUE TITLE
Order problems with apt update

### ISSUE THREAD

**Issue by ITler** [voxpupuli/puppet-zabbix#233]
Hy,

I use zabbix module together with other modules (puppetlabs official, modules from other people and organizations, my own).
Like yours, other modules also include vendor's package repository. Therefore the workflow usually is (for debian based nodes):

1. define apt sources,
2. then do apt-get update,
3. then install module package(s), i.e. `package { 'zabbix-agent': }

Obviously in my setup this workflow works while composing all the different 3rd party modules, except the zabbix module :)

While tracking down my issues I've tried to work-around them, which was leading to ugly dependency cycles. I ended up with comparing your repo.pp with the one's from [postgresql] and [nginx] and recognized, that the mentioned workflow isn't implemented. As the zabbix module handles multiple package files (server, agent, ...) the approach used in [postgresql module](https://github.com/puppetlabs/puppetlabs-postgresql/blob/master/manifests/repo/apt_postgresql_org.pp#L21-L22) might be most convenient, as it works with explicit tagging.

Would you agree? PR needed

**Comment by bastelfreak** [comment]
I don't quite understand the issue here. The module handles the zabbix.com repo and the package installation. Do you want to define the repo by yourself? Or is the update missing?

**Comment by ITler** [comment]
Jep, the update is missing. This raises when using zabbix module together with other modules. In my setup it happens, that zabbix agent was installed to early. The PR #234 solves this.

**Comment by bastelfreak** [comment]
thanks for the fix! merged and close.

**Comment by ITler** [comment]
thanks for accepting PR
