### ISSUE TITLE
Custom config file name/path

### ISSUE THREAD

**Issue by fgallese** [voxpupuli/puppet-zabbix#240]
Please check the following items before submitting an issue -- thank you!

Note that this project is released with a Contributor Code of Conduct.
By participating in this project you agree to abide by its terms.
[Contributor Code of Conduct](https://voxpupuli.org/coc/).

- [x] There is no existing issue or PR that addresses this problem

Optional, but makes our lives much easier:

- [x] The issue affects the latest release of this module at the time of
  submission

- - -

### What are you seeing

When using a non-default value for either agent or server configuration file, the file it's created, but it is not referenced at the init script. This causes the daemon to use the default values "/etc/zabbix/zabbix_agentd.conf", therefore, the daemon cant start or it starts using the default configuration file which hasn't the custom settings.

### What behaviour did you expect instead

It should set __DAEMON_OPTS="-c [CUSTOMCONFIGFILE]"__ at the init script, so you can use this:

start-stop-daemon --oknodo --start --pidfile $PID --exec $DAEMON **-- $DAEMON_OPTS** >/dev/null 2>&1

At the start function.

### How did this behaviour get triggered

When changing the default values for zabbix config files.

### Output log

N/A

### Any additional information you'd like to impart

N/A

**Comment by bastelfreak** [comment]
I'm just curious, can you tell me why you set a custom config path?

**Comment by bastelfreak** [comment]
#246 got merged

**Comment by jk2l** [comment]
This break 14.04. Systemd is not being used yet in 14.04. The code removed /etc/init.d/zabbix-agent and now the service won't start

**Comment by fgallese** [comment]
@jk2l: I'll add a check for Ubuntu so it takes it into account when detecting the SO, currently it checks "$::osfamily == 'debian'".

**Comment by jk2l** [comment]
Actually i created a patch https://github.com/voxpupuli/puppet-zabbix/pull/252 also done a bit refactoring

**Comment by fgallese** [comment]
@jk2l :+1:
