### ISSUE TITLE
Release 999.999.999 version of wdijkerman for deprecation

### ISSUE THREAD

**Issue by rnelson0** [voxpupuli/puppet-zabbix#243]
https://forge.puppet.com/wdijkerman/zabbix 2.2.1 does reference the migration to the puppet namespace, but is not version 999.999.999. This is part of our [migrating instructions](https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli).

**Comment by dj-wasabi** [comment]
I just pushed version 999.999.999 to the forge. (Sorry for the late action)

**Comment by rnelson0** [comment]
Thanks!
