### ISSUE TITLE
related to #305 run fails if system does not have systemd fact

### ISSUE THREAD

**Issue by vchan2002** [voxpupuli/puppet-zabbix#310]
It would appear that, with #305, does not work on systems that does not have the systemd fact.

A workaround we did for now is creating a fact called systemd on our own....

Is that fact supposed to be set somewhere using this, or some other puppet module?  

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: str2bool(): Wrong number of arguments given (0 for 1) at /etc/puppet/envs/staging/modules/zabbix/manifests/agent.pp:331 on node -----
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.7.5
- Ruby: 2.0.0
- Distribution: Amazon Linux
- Module version: 2.6

**Comment by gyoza** [comment]
I can confirm this is accurate and true. I have experienced this myself.

**Comment by vchan2002** [comment]
NM... I see the dependency to the systemd module that provides the fact....

**Comment by tdac** [comment]
Hi - I'm still seeing this on buntu 14.04.5 despite having camptocamp/systemd on the puppetmaster.   Can anyone give me a steer as to how to resolve this issue?

**Comment by AHPyXA** [comment]
Faced the same issue.
> Notice: Module camptocamp-systemd 0.4.0 is already installed.

Is it may be puppet/facter version related?
OS - ubuntu 14.04
With puppet 3.4.3 and facter 1.7.5 from ubuntu repo I got the problem
With puppet 3.8.7 and facter 2.4.6 from puppetlabs the problem is gone

**Comment by bastelfreak** [comment]
Hi @AHPyXA,

We don't support facter 1.X and puppet 3.X anymore. Facter 1.X doesn't support the used hash syntax, also there are multiple puppet4 types used. Puppet3 is end of life since January, everybody should really upgrade. Feel free to join our IRCchannle #voxpupuli on freenode if you've any questions about upgrading puppet.
