### ISSUE TITLE
Integer 18455137360 too big to convert to "int" at manifests/params.pp:333:24

### ISSUE THREAD

**Issue by suslikas** [voxpupuli/puppet-zabbix#329]
Hi,

with puppet-zabbix module v2.4.0 all fine, after update to 2.6.1 I got error

Error while evaluating a Function Call, integer 18455137360 too big to convert to `int' at /etc/puppetlabs/code/environments/csinlb6/modules/zabbix/manifests/params.pp:333:24

CentOS release 6.8
puppet-agent-1.3.6-1.el6.x86_64
gem list --local | grep stdlib
stdlib (0.1.0)

**Comment by bastelfreak** [comment]
Hi,
you have a puppet module called stdlib, can you tell us the version of it? It provides the function that failes here. There are known issues with older versions.

**Comment by suslikas** [comment]
puppetlabs/stdlib 4.6.0

**Comment by alexjfisher** [comment]
It might actually be the puppet server containing the bug.  @suslikas Do you know what version you use?
Are you hitting https://tickets.puppetlabs.com/browse/SERVER-1408 ?

**Comment by suslikas** [comment]
Temporary I'm switch stdlib to 4.13.0, it's work, but we need lot of time to check all other modules for compatible with this version, will be very nice to leave version as 4.6.0.

**Comment by suslikas** [comment]
We update stdlib and now all work fine.
