### ISSUE TITLE
Missing code to support server parameter 'StartEscalators'

### ISSUE THREAD

**Issue by alexjhart** [voxpupuli/puppet-zabbix#340]
Using latest module version: 2.6.1

I'm trying to do this:

```puppet
class { 'zabbix::server':
  startescalators => '2',
}
```

But get this error:

```
Error while evaluating a Resource Statement, Class[Zabbix::Server]: has no parameter named 'startescalators'
```

Instead of this change happening:

```
StartEscalators=2 added to /etc/zabbix/zabbix_server.conf
```

It looks like some support was added for this parameter in templates/zabbix_server.conf.erb last year by @ericsysmin, but was never completed in init.pp, etc. 

Is this a quick fix for someone or should I give it a go?

**Comment by LorkMurillo** [comment]
Hello, I have the same problem.

I have solved it by adding startescalators variable in params.pp and server.pp

server.pp (new line 327):
`   $startescalators = $ zabbix :: params :: server_startescalators,`

params.pp (new line 162):
`   $server_startescalators = '1'`

Output:

```
Notice: /Stage[main]/Zabbix::Server/File[/etc/zabbix/zabbix_server.conf]/content:
--- /etc/zabbix/zabbix_server.conf	2017-01-25 00:00:34.031630747 +0100
+++ /tmp/puppet-file20170125-21315-1ubfsll	2017-01-25 01:21:10.244719545 +0100
@@ -152,7 +152,7 @@
 ### Option: StartEscalators
 #   Number of pre-forked instances of escalators.
 #
-
+StartEscalators=10
```

Regards
