### ISSUE TITLE
zabbix::web Could not find user zabbix

### ISSUE THREAD

**Issue by giedriusramas** [voxpupuli/puppet-zabbix#341]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8.1
- Ruby: 2.3
- Distribution: Ubuntu 16.04.1 LTS
- Module version: latest commit 1093d94 

## How to reproduce (e.g Puppet code you use)
distributed zabbix web fronted only.

```
  class { 'apache':
    mpm_module => 'prefork',
  }
  class { 'apache::mod::php': }
  class { 'zabbix::web':
    web_config_owner => 'www-data',
    web_config_group => 'www-data',
    zabbix_url       => $::ipaddress,
    zabbix_server    => 'zabbix-server',
    database_host    => 'zabbix-db',
    database_type    => 'mysql',
    manage_resources => true,
    apache_use_ssl   => true,

  }
}
```

## What are you seeing

```
Info: Applying configuration version '1484052344'
Error: Could not find user zabbix
Error: /Stage[main]/Zabbix::Web/File[/etc/zabbix/web]/owner: change from www-data to zabbix failed: Could not find user zabbix
Error: Could not find group zabbix
Error: /Stage[main]/Zabbix::Web/File[/etc/zabbix/web]/group: change from root to zabbix failed: Could not find group zabbix
Notice: /Stage[main]/Zabbix::Web/File[/etc/zabbix/web/zabbix.conf.php]: Dependency File[/etc/zabbix/web] has failures: true
Warning: /Stage[main]/Zabbix::Web/File[/etc/zabbix/web/zabbix.conf.php]: Skipping because of failed dependencies

```

## Any additional information you'd like to impart
https://github.com/voxpupuli/puppet-zabbix/blob/master/manifests/web.pp#L349-L355

changing owner and group from zabbix to www-data solves the issue.

**Comment by rnelson0** [comment]
I believe the zabbix user comes from the zabbix package install, not from this class. Can you double check to make sure the rpm/deb/whatever did not have an issue running the post-install/upgrade script, or that additional manual efforts were not taken afterward that would affect that?

**Comment by giedriusramas** [comment]
In my case I use distributed zabbix. 4 multiple-node zabbix. In the node I have only Zabbix Web frontend zabbix-frontend-php installed. That package appears to won't create zabbix user.

**Comment by rnelson0** [comment]
For now, you will want to manage the user/group as resources in your manifest. I'm not particularly well versed in this module, so I am not sure if those resources can be effectively managed by the module or not, or when that might be added.
