### ISSUE TITLE
Zabbix 3.0 on Centos 6.x

### ISSUE THREAD

**Issue by xdexter** [voxpupuli/puppet-zabbix#359]
Hello, 

There are some planning to add suport to Centos 6.x with Zabbix 3.0 in this module?

Best,

**Comment by alexjfisher** [comment]
This *should* already work.  Unless you're using puppet 3 and EL6's very old ruby 1.8 that is.  What error do you get?

**Comment by xdexter** [comment]
Hello @alexjfisher,

Sorry but i readed the requeriments and did not have support to Centos 6.x, so i did not try yet, understand?

Yes, i use Centos 6.8, Epel 6.8 and Ruby 1.8.7.

Best;

**Comment by bastelfreak** [comment]
Hi @xdexter. The latest release of the module supports zabbix 3.0 and 3.2, I'm going to close this issue. Please let us know if you experience any new issues. Please keep in mind that we don't support puppet3/ruby1.8 since december.
