### ISSUE TITLE
Zabbix Repository (zabbix-non-supported) defined with incorrect gpgkey

### ISSUE THREAD

**Issue by jamescook000** [voxpupuli/puppet-zabbix#397]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.1
- Ruby: 2.0.0p648
- Distribution: Centos 7
- Module version: 4.0.0

## How to reproduce (e.g Puppet code you use)

The code used is straight from the modules example:

  class { 'apache':
    mpm_module => 'prefork',
  }
  include apache::mod::php
  class { 'postgresql::server': }
  class { 'zabbix':
    zabbix_version => '3.2',
    zabbix_url        => 'localhost',
  }

## What are you seeing

When trying to install any rpm from the  zabbix-nonsupported repository it fails with the following GPG key error message:

The GPG keys listed for the "Zabbix_nonsupported_7_x86_64" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.

## What behaviour did you expect instead

No errors and Zabbix to install as per module.

## Output log

Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install zabbix-server-pgsql' returned 1: warning: /var/cache/yum/x86_64/7/Zabbix_nonsupported_7_x86_64/packages/fping-3.10-1.el7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 79ea5ed4: NOKEY

The GPG keys listed for the "Zabbix_nonsupported_7_x86_64" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.

 Failing package is: fping-3.10-1.el7.x86_64
 GPG Keys are configured as: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
Error: /Stage[main]/Zabbix::Server/Package[zabbix-server-pgsql]/ensure: change from purged to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install zabbix-server-pgsql' returned 1: warning: /var/cache/yum/x86_64/7/Zabbix_nonsupported_7_x86_64/packages/fping-3.10-1.el7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 79ea5ed4: NOKEY

The GPG keys listed for the "Zabbix_nonsupported_7_x86_64" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.

 Failing package is: fping-3.10-1.el7.x86_64
 GPG Keys are configured as: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591

## Any additional information you'd like to impart

This is due to commit ac9002ccaf8dd8257f1d74fc5072d44117f4c9b6 modifying the GPG key for Zabbix 3.2+ for both the Zabbix and Zabbix-nonsupported repository.

However the Zabbix-nonsupported should have remained unmodified as the GPG key was never changed by Zabbix SIA (gpgkey => 'http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX')

**Comment by bastelfreak** [comment]
Hi @jamescook000, thanks for the bugreport. I'm currently working on a fix. Hopefully I can push it today.

**Comment by bastelfreak** [comment]
Hi @jamescook000, can you take a look at the PR and test if this resolves your issue?

**Comment by jamescook000** [comment]
HI,

Yes thanks the code updates and I have tested and it does resolve the issue.

Cheers
James

**Comment by bastelfreak** [comment]
Thanks for the feedback!

**Comment by frenchtoasters** [comment]
Sorry just noticed this, i found that i was using on version back after this and that had the fix IIRC.
