### ISSUE TITLE
Fails to upgrade zabbix-agent if zabbix_version is changed

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-zabbix#398]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.1
- Ruby: 2.4.1
- Distribution: CentOS
- Module version: master branch

## How to reproduce (e.g Puppet code you use)

Execute this:

```puppet
class{'zabbix-agent':
  zabbix_version => '2.4'
}
```

Than do an upgrade like this:

```puppet
class{'zabbix-agent':
  zabbix_version => '3.2'
}
```

## What are you seeing

zabbix not beeing updated

## What behaviour did you expect instead

zabbix updated to the specified version

## Any additional information you'd like to impart

The package zabbix-agent will never be upgraded since the default behaviour of the package resource is `present`, not `latest`: https://github.com/voxpupuli/puppet-zabbix/blob/master/manifests/params.pp#L71

**Comment by alexjfisher** [comment]
I guess that parameter isn't meant to specify the package version, but is used elsewhere for generating compatible configuration for example?  Maybe add a parameter zabbix_package_version that can default to 'present'?
