### ISSUE TITLE
zabbix::agent LogType and User are not valid in 2.2 (EPEL)

### ISSUE THREAD

**Issue by TJM** [voxpupuli/puppet-zabbix#417]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: PE 2016.4
- Ruby: embedded
- Distribution: RHEL 7.3
- Module version: 4.1.2

## How to reproduce (e.g Puppet code you use)
include ::zabbix::agent

```
---
zabbix::agent::manage_repo: false
zabbix::agent::zabbix_agent_package: zabix22-agent
zabbix::agent::agent_configfile_path: /etc/zabbix-agentd.conf
```

## What are you seeing
Zabbix agent won't start due to invalid parameters in config file.

## What behaviour did you expect instead
it to start.

## Output log
(dont have this handy)

## Any additional information you'd like to impart

We tried setting zabbix::agent::logtype: false
and even tried setting it to: '' (empty string). false fails because it is typed to "String" and of course "" is apparently *true* in ruby (wth).

I think this could be resolved by perhaps making the type something like `Variant[Boolean, String]` ? For at least "LogType" and "User" (these are the two parameters we have to comment out to get zabbix agent to start.

Thanks in advance,
Tommy

**Comment by bastelfreak** [comment]
Hi @TJM, thanks for rising this issue. Is there any reason for using this outdated agent? Also why do you use it from epel and not the official repos?

You can set zabbix::agent::zabbix_version to 2.2, this will exclude the User and LogType option from the config file.

**Comment by TJM** [comment]
Hi @bastelfreak,

Thanks for your response! As to the "why" question, I can only answer that corporations and government are very rarely on the bleeding edge. Often the servers do not have direct Internet access, so accessing the EPEL repo, which is used by several other services was just "handy" :)

We had actually tried to set that as well, but missed the key name slightly, we had `zabbix::agent::version`.  Sorry for the noise!

This is resolved!
~tommy

**Comment by TJM** [comment]
For what its worth, the extra "zabbix_" and also "agent_" in some of the keys could lead to confusion, but I think changing them now is really not an option :)
