### ISSUE TITLE
Syntax Error at line 82 in file init.pp

### ISSUE THREAD

**Issue by danirueda** [voxpupuli/puppet-zabbix#423]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.6.2
- Ruby: ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
- Distribution: CentOS Linux release 7.2.1511 (Core)
- Module version: 4.1.3

## How to reproduce (e.g Puppet code you use)
```
node 'zabbix.example.com' {
  class { 'apache':
    mpm_module => 'prefork',
  }
  include apache::mod::php

  class { 'mysql::server': }

  class { 'zabbix':
    zabbix_url    => 'zabbix.example.com',
    database_type => 'mysql',
  }
}

class{'zabbix::agent':
  zabbix_version       => '3.2',
  manage_repo          => true,
  zabbix_package_state => 'latest',
}
```

## What are you seeing
A syntax error in module file $HOME/.puppet/modules/zabbix/manifests/init.pp while my manifest is running.
## What behaviour did you expect instead
I expect a good instalation of php, mysql, apache, zabbix server and agent in 3.2 version.
## Output log
`Error: Syntax error at 'zabbix'; expected ')' at /home/a559207/.puppet/modules/zabbix/manifests/init.pp:82 on node zabbix.example.com`
## Any additional information you'd like to impart
It's strange for me get an error for the module file being this module approved and official.
It doesn't seem that there been a syntax error,  I have checked the file and it seems that syntax is ok.

**Comment by bastelfreak** [comment]
Hi @danirueda, you are using a way outdated puppet version. Support for puppet 3.X ended last december. Puppetlabs doesn't provide any patches for that version, and puppet 5 just got released. This module isn't compatible anymore with puppet 3. You should really consider updating your environment. We're reachable basically 24/7 in the IRC channel #voxpupuli on freenode. Just let us know if you need any help for the upgrades.

**Comment by danirueda** [comment]
@bastelfreak Thanks! I was very confused. You can close the issue.
