### ISSUE TITLE
SenderFrequency parameter is deprecated in Zabbix 3.4

### ISSUE THREAD

**Issue by marcinbojko** [voxpupuli/puppet-zabbix#437]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.x
- Ruby: 2.0.0p648
- Distribution: CentOS 7.x
- Module version: 4.1.3

## How to reproduce (e.g Puppet code you use)

Use module in version 4.1.3 to manage Zabbix in version 3.4

## What are you seeing
_ zabbix config
-#SenderFrequency=30
+SenderFrequency=30

## What behaviour did you expect instead

-zabbix config
-SenderFrequency=#
-

## Output log

> zabbix_server[2537]: zabbix_server [2537]: unknown parameter "SenderFrequency" in config file "/etc/zabbix/zabbix_server.conf", line 228
zabbix-server.service: main process exited, code=exited, status=1/FAILURE

## Any additional information you'd like to impart

In Zabbix 3.4 parameter SenderFrequency is deprecated.
Parameter still exists in /zabbix/templates/zabbix_server.conf.erb

Proposed change 
from:

```
### Option: SenderFrequency
#   How often Zabbix will try to send unsent alerts (in seconds).
#
SenderFrequency=<%= @senderfrequency %>
```

to

```
<% if @zabbix_version.to_f <= 3.2 %>
### Option: SenderFrequency
#   How often Zabbix will try to send unsent alerts (in seconds).
#
SenderFrequency=<%= @senderfrequency %>
<% end %>
```

**Comment by Heidistein** [comment]
This is fixed in 
https://github.com/voxpupuli/puppet-zabbix/pull/436
