### ISSUE TITLE
Install php modules required by Zabbix

### ISSUE THREAD

**Issue by Bouke** [voxpupuli/puppet-zabbix#439]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.4
- Ruby: ?
- Distribution: Ubuntu 16.04
- Module version: 4.1.3

## How to reproduce (e.g Puppet code you use)
```
node 'zabbix.example.com' {
  class { 'apache':
    mpm_module => 'prefork',
  }
  include apache::mod::php

  class { 'postgresql::server': }

  class { 'zabbix':
    zabbix_url    => 'zabbix.example.com',
  }
}
```

## What are you seeing
Errors in the log (`/var/log/apache2/{url}_error.log`) indicating that certain php modules are expected, but not installed.

## What behaviour did you expect instead
Correct php modules being installed (similar to `php-pgsql`)

**Comment by trevorrea** [comment]
Hi,

I don't think this is something that the module developers should fix.  You could fix this by using the following code or similar


```
  $packages = ['php7.0-bcmath','php7.0-mbstring','php7.0-xml']

  package { $packages:
    ensure  => 'installed',
    require => Class['zabbix'],
  }

}
```

**Comment by Fabian1976** [comment]
Or use a profile (profile::zabbix::web) and add this to the profile:
```include apache::mod::php```
