### ISSUE TITLE
Allow external script execution with SE Linux

### ISSUE THREAD

**Issue by tux-o-matic** [voxpupuli/puppet-zabbix#441]
The current SE Linux [module](https://github.com/voxpupuli/puppet-zabbix/blob/master/files/zabbix-agent.te) doesn't seem to be enough to let the Zabbix agent execute scripts.
```bash
allow zabbix_t zabbix_script_exec_t : file { ioctl read getattr execute open } ;
```
And the File resource agent::includedir should probably get the right selinux parameters for the rule to apply.

**Comment by bastelfreak** [comment]
Hi @tux-o-matic, thanks for this request. Are you able to provide a patch for this?

**Comment by tux-o-matic** [comment]
Should be able to. Will create a PR.

**Comment by tux-o-matic** [comment]
A lead maybe:
https://bugzilla.redhat.com/show_bug.cgi?id=1380697
