### ISSUE TITLE
Dependencies need update

### ISSUE THREAD

**Issue by fox887** [voxpupuli/puppet-zabbix#453]
Many modules were upgraded but puppet-zabbix is incompatible with some dependencies.

Warning: Module 'puppetlabs-apache' (v2.1.0) fails to meet some dependencies:
  'puppet-zabbix' (v5.0.0) requires 'puppetlabs-apache' (>= 1.6.0 < 2.0.0)
Warning: Module 'puppetlabs-apt' (v4.1.0) fails to meet some dependencies:
   'puppet-zabbix' (v5.0.0) requires 'puppetlabs-apt' (>= 2.1.0 < 3.0.0)
Warning: Module 'puppetlabs-concat' (v4.0.1) fails to meet some dependencies:
  'puppet-zabbix' (v5.0.0) requires 'puppetlabs-concat' (>= 2.2.1 < 3.0.0)

├──puppet-zabbix (v5.0.0)
├── puppetlabs-apache (v2.1.0)  invalid
├── puppetlabs-apt (v4.1.0)  invalid
├── puppetlabs-concat (v4.0.1) invalid

**Comment by bastelfreak** [comment]
Hi @fox887, thanks for this issue. are you able to provide a patch for this?

**Comment by juniorsysadmin** [comment]
Most of these except for maybe concat should be soft, soft and soft dependencies #330

**Comment by fox887** [comment]
I have changed the metadata.json manually to use the versions I have installed on my server and couldn't find any problem.

puppetlabs-apache' (v2.1.0)
puppetlabs-apt' (v4.1.0)
puppetlabs-concat' (v4.0.1)

I need more time to take a look at the code more deeply and check the changelog of those modules to understand what they have changed.
