### ISSUE TITLE
zabbix::agent without an IP shouldn't guess the IP

### ISSUE THREAD

**Issue by tibers** [voxpupuli/puppet-zabbix#473]
https://github.com/voxpupuli/puppet-zabbix/blob/master/manifests/agent.pp#L293-L307

This is bad because if we're using this module when building containers for docker/kubernetes/etc, the module will grab the temporary IP of the VM in the build service, which will be incorrect when the container is deployed one or more times into a production environment. 
  
Omitting the ListenIP line entirely makes the agent pick whatever IP it thinks is appropriate, so it's a much cleaner solution.

**Comment by bastelfreak** [comment]
Hi @tibers, thanks for rising this issue. Are you able to create a pull request with the needed changes?

**Comment by tibers** [comment]
I'm not entirely sure I understand the code enough to make this happen but I'll give it a go. :)

**Comment by tibers** [comment]
Opened [this PR](https://github.com/voxpupuli/puppet-zabbix/pull/474), hopefully I didn't goose things up too badly....

**Comment by Helenofpern** [comment]
Any news on when this will be implemented as it is a right pain when managing aws instances across many accounts.

**Comment by bastelfreak** [comment]
This should be fixed with https://github.com/voxpupuli/puppet-zabbix/pull/487
