### ISSUE TITLE
listenip in agent not resolv to address from networl face name

### ISSUE THREAD

**Issue by glafir** [voxpupuli/puppet-zabbix#493]
Hello!
A upgraded puppet-zabbix (v4.1.3 -> v6.3.0) then "listenip" in agent not resolv to address from networl face name.
In zabbix-agent config
ListenIP=enp0s18

But it is not IP-address. How I can resolve this problem?

**Comment by bastelfreak** [comment]
Hi @glafir, thanks for rising this issue. Can you provide the code you use to call this module? I assume you set explicitly set listenip?

The used regex doesn't match your network name:

https://github.com/voxpupuli/puppet-zabbix/blob/3ac150d8ca91556c5db19770ba7648a27b17ee0f/manifests/agent.pp#L298

I think that's the issue.

**Comment by bastelfreak** [comment]
@glafir  I proposed a fix in https://github.com/voxpupuli/puppet-zabbix/pull/494, could you test that?

**Comment by glafir** [comment]
Oh, Yes, yes!
I forget for this,
I change it in pre-versions.

so I did it

  $listen_ip = $listenip ? {
    /^(eth|lo|bond|ens|enp|lxc|eno|vmbr|tap|tun|virbr).*/ => fact("networking.interfaces.${listen_ip}.ip"),
    '*' => undef,
    default => $listenip,
  }

But listenIP now is empty (((

**Comment by bastelfreak** [comment]
I updated my patch. There is currently a typo in the code. Can you test it again? Can you paste the code you use to call the zabbix::agent class?

**Comment by glafir** [comment]
It not working now. In zabbix-conf

+ListenIP=enp0s18

(((

**Comment by glafir** [comment]
But if I write in regex my inet-faces, I get empty $listenIP
For example

/^(eth|lo|bond|lxc|ens|enp|vmbr|eno|tap|tun|virbr).*/ =>  .....

**Comment by glafir** [comment]
Oh, Yes!
It is working now for me!

/^(eth|lo|bond|lxc|ens|enp|vmbr|eno|tap|tun|virbr).*/ => fact("networking.interfaces.${$listenip}.ip"),

Add please to repo! Thanks!

**Comment by glafir** [comment]
Full-code in listenip-section

  $listen_ip = $listenip ? {
    /^(eth|lo|bond|lxc|ens|enp|vmbr|eno|tap|tun|virbr).*/ => fact("networking.interfaces.${$listenip}.ip"),
    '*' => undef,
    default => $listenip,
  }

**Comment by bastelfreak** [comment]
We can do a new release as soon as https://github.com/voxpupuli/puppet-zabbix/pull/494 got reviewed and merged
