### ISSUE TITLE
repeated attempted key import in Ubuntu 18.04

### ISSUE THREAD

**Issue by anthonysomerset** [voxpupuli/puppet-zabbix#500]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.4.0
- Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
- Distribution: Ubuntu Bionic (18.04 LTS)
- Module version: 6.3.1

## How to reproduce (e.g Puppet code you use)
Include Zabbix Agent class on a clean Ubuntu 18.04 install - run puppet agent -t multiple times

## What are you seeing
note repeated attempts to import GPG key:
`Notice: /Stage[main]/Zabbix::Repo/Apt::Key[zabbix-FBABD5F]/Apt_key[zabbix-FBABD5F]/ensure: created`

## What behaviour did you expect instead
FIrst run might import it (or not), further puppet runs should report no changes
## Output log
```
Debug: Executing: '/usr/bin/apt-key adv --list-keys --with-colons --fingerprint --fixed-list-mode'
Debug: Executing: '/usr/bin/gpg --with-fingerprint --with-colons /tmp/apt_key20180514-28907-1bfwcdf | awk -F: '/^fpr:/ { print $10 }''
Debug: Executing: '/usr/bin/apt-key add /tmp/apt_key20180514-28907-1bfwcdf'
Notice: /Stage[main]/Zabbix::Repo/Apt::Key[zabbix-FBABD5F]/Apt_key[zabbix-FBABD5F]/ensure: created
Debug: /Stage[main]/Zabbix::Repo/Apt::Key[zabbix-FBABD5F]/Apt_key[zabbix-FBABD5F]: The container Apt::Key[zabbix-FBABD5F] will propagate my refresh event
Debug: Apt::Key[zabbix-FBABD5F]: The container Class[Zabbix::Repo] will propagate my refresh event
```
## Any additional information you'd like to impart
it would seem that this particular key has been entirely deprecated and should not be included on Ubuntu 18.04 installs

**Comment by bastelfreak** [comment]
Hi @anthonysomerset, thanks for bringing this up. We currently don' test the module against Ubuntu 18.04. Are you able to provide a patch for this?

**Comment by anthonysomerset** [comment]
I've just started looking at this and quite frankly it has me stumped

1) on clean Ubuntu 18.04 VM with the module included i see both keys are in apt's key list fine and i see both keys exist in the referenced public key file accordingly - apt has no issues, only puppet repeatedly attempting to import this specific key.

2) this makes me believe that this issue might now exist upstream with the apt module which kind of makes sense because there are other bugs with ubuntu 18.04

**Comment by anthonysomerset** [comment]
i can confirm that it would appear that https://github.com/puppetlabs/puppetlabs-apt/pull/764 resolves this issue upstream - i guess we just have to wait for a point release from the upstream module
