### ISSUE TITLE
AIX Support

### ISSUE THREAD

**Issue by TJM** [voxpupuli/puppet-zabbix#504]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Puppet Enterprise 2018.1.0 (puppet-agent-5.5.1)
- Ruby: ruby 2.4.3p205 (2017-12-14 revision 61247) [powerpc-aix7.1.0.0]
- Distribution: 7100-05-02-1810
- Module version: 6.1.0

## How to reproduce (e.g Puppet code you use)

```
include zabbix::agent
```

## What are you seeing
Documentation indicates that AIX is not supported.

## What behaviour did you expect instead
AIX supported for at least Zabbix Agent(*)

## Output log
N/a

## Any additional information you'd like to impart
We are going to look into this, in the next month or three, but this is to gather support/interest.

**Comment by bastelfreak** [comment]
Hi @TJM, we don't have any AIX machine for tests. We happily merge enhancements that make it work on AIX.
