### ISSUE TITLE
The topic is wrong!

### ISSUE THREAD

**Issue by aminmaghsodi** [voxpupuli/puppet-zabbix#517]
You set the topic name to "Multi node Zabbix Server", but actually you did it for zabbix-frontend-php and it is not multi zabbix server. You have only 1 zabbix server in 1 machine and multi web interface on some machines.

**Comment by baurmatt** [comment]
@aminmaghsodi Was this meant to be a comment on another issue?

**Comment by aminmaghsodi** [comment]
Sorry it was a fault!
