### ISSUE TITLE
zabbix_template resource doesn't work with Zabbix 4.0

### ISSUE THREAD

**Issue by gdubicki** [voxpupuli/puppet-zabbix#556]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.2
- Ruby: incuded in ^ puppet
- Distribution: Centos 7
- Module version: 6.5.0

## How to reproduce (e.g Puppet code you use)

```
zabbix_template { $name:
      template_source => "${template_dir}/${name}.xml",
      zabbix_url      => $zabbix_wrapper::server::config['zabbix_url'],
      zabbix_user     => $zabbix_wrapper::server::api_user,
      zabbix_pass     => $zabbix_wrapper::server::api_pass,
      apache_use_ssl  => true,
}
```
..with appropriate values to access my Zabbix instance API.

## What are you seeing

```
Error: /Stage[main]/Zabbix_wrapper::Server::Templates/Zabbix_template[MY_TEMPLATE]: Could not evaluate: Zabbix API version: 4.0.0 is not support by this version of zabbixapi
```

## What behaviour did you expect instead

It should work as 6.5.0 adds Zabbix 4.0 compatibility.

## Any additional information you'd like to impart

I assume that this is a problem with `zabbixapi` gem, so I have already created https://github.com/express42/zabbixapi/issues/91 , but that project seems to have a problem with maintenance (https://github.com/express42/zabbixapi/issues/88), so it would be great if you guys do something about it (I would love to help but Ruby is my weak spot...).

**Comment by bastelfreak** [comment]
Sorry, but I'm not really sure how we can help out here :(.

**Comment by gdubicki** [comment]
Maybe we should switch puppet-zabbix to a fork of zabbixapi with removed hard-coded list of supported Zabbix versions until zabbixapi starts to be maintained again, @bastelfreak ?

PS We should mark this issue as a bug as https://github.com/voxpupuli/puppet-zabbix/blob/master/CHANGELOG.md states that this module is Zabbix 4.0-compatible since v6.5.0.

**Comment by bastelfreak** [comment]
as long as a fork is available on rubygems and we can properly depend on and, that would be fine.
