### ISSUE TITLE
Add historyindexcachesize to class zabbix

### ISSUE THREAD

**Issue by Ordnaxz** [voxpupuli/puppet-zabbix#566]
Currently, there's no way of setting "historyindexcachesize" when using the class zabbix. An (unwanted) workaround is to use zabbix::server instead. 

Could the historyindexcachesize option please be added under class::zabbix in init.pp? Other options such as "historycachesize" are already available under said class.

**Comment by bastelfreak** [comment]
Hi @Ordnaxz, thanks for bringing this up. Can you create a PR for this?
