### ISSUE TITLE
Incompatibility with puppetlabs-apt (starting from 6.1.0 version )

### ISSUE THREAD

**Issue by catsem** [voxpupuli/puppet-zabbix#569]
After upgrading puppetlabs-apt to 6.1.0 or later, I'm facing following issue:

Error: Could not retrieve catalog from remote server: 

Error 500 on SERVER: Server Error: no parameter named 'refresh' at /etc/puppetlabs/code/environments/production/modules/apt/manifests/key.pp:51 on Apt_key[rear] at /etc/puppetlabs/code/environments/production/modules/apt/manifests/key.pp:51 on node foo.bar

Seems like the refresh is called the wrong way. -> https://tickets.puppetlabs.com/browse/MODULES-8019

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.9
- Ruby: 
- Distribution: Ubuntu 16.04
- Module version: 6.6.0

## How to reproduce (e.g Puppet code you use)
classes:
  zabbix::agent: 

## What are you seeing
Error 500 on SERVER: Server Error: no parameter named 'refresh' at /etc/puppetlabs/code/environments/production/modules/apt/manifests/key.pp:51 on Apt_key[rear] at /etc/puppetlabs/code/environments/production/modules/apt/manifests/key.pp:51 on node foo.bar

## What behaviour did you expect instead
Agent run without error

**Comment by baurmatt** [comment]
Are you sure this happens due to the `zabbix` agent module? `Apt_key[rear]` isn't a resource in `zabbix` module.

**Comment by catsem** [comment]
Uhh sorry my mistake. This is the error I wanted to show:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'refresh' at /etc/puppetlabs/code/environments/production/modules/apt/manifests/key.pp:51 on Apt_key[zabbix-FBABD5F] at /etc/puppetlabs/code/environments/production/modules/apt/manifests/key.pp:51 on node foo.bar

I guess that with the later versions of puppetlabs-apt you have to put the apt::key below a apt::source element. Thats what I did to fix the error with my private "rear" module.

**Comment by bastelfreak** [comment]
Hi @catsem. Can you provide a PR to fix  this?

**Comment by alexjfisher** [comment]
This looks like an environment isolation issue to me.

The new parameter is both added to the [type](https://github.com/puppetlabs/puppetlabs-apt/pull/795/files#diff-2e4991e5a1379264a65bf0ee1dc4be10R78) and used in a [manifest](https://github.com/puppetlabs/puppetlabs-apt/pull/795/files#diff-fbfb4772af907a89b73a9df7b206dc8dR53) in the same PR.

But you then get the error that the parameter doesn't exist (because it didn't when puppetserver loaded the code).
You must run `puppet generate types` to solve this sort of issue. See https://puppet.com/docs/puppet/5.4/environment_isolation.html#generate-types

**Comment by catsem** [comment]
@alexjfisher 
Thats the solution. Thanks for the hint. Running **puppet generate types** resolved the issue.
Running puppet for ages and never faced this bevore...

**Comment by francesco2013** [comment]
Hello I am facing the very same problem. But the very weird thing in my case is that within the same environment (Production) all other agents (they all run the same version 4.10.10) dont have this error. 
Nothing changed and only one agent on one specific machine gives this error.  
I am not a puppet expert and I am frankly a bit scared of trying to issue puppet generate types on the puppet server. My fear is to screw up all other environments and agents. I never had a problem it came out today all of a sudden and from one only specific agent on one only specific machine. 

Could you please advise me ? Thanks in advance.

**Comment by baurmatt** [comment]
Try using `puppet generate types`. You can get rid of the generated files by running:

```
rm -rf /etc/puppetlabs/code/environments/*/.resource_types/
```

**Comment by francesco2013** [comment]
Thanks for your answer baurmatt but that does not explain why all other agents that are identical are working and not this specific one. I would do that command if they would all fail. There must be something wrong with one agent. As I said I am terrified by the idea of screwing up the puppet server setup ...

**Comment by baurmatt** [comment]
> Is that command 100% safe meaning it wont make the other agents stop working?

It just ensure your types are environment save. --> https://puppet.com/docs/puppet/5.4/environment_isolation.html

> Do the clients need to be all stopped while I run that on the puppet server?

No. We run it for every deployment we do. Probably a couple of hundred times a day.

 > Which user should run the command on the puppet server ? root ? puppet ?

The user which you use for deploying you Puppet code.

**Comment by eimlav** [comment]
@alexjfisher has it spot on. This specific environment isolation issue has been observed by other people ([see ticket](https://tickets.puppetlabs.com/browse/MODULES-8019)) and all those affected were able to rectify the issue with `puppet generate types` command. If you would like additional information on environment isolation and how to remedy these issues please see [here](https://puppet.com/docs/puppet/5.3/environment_isolation.html). I hope this helps you out @francesco2013 !

**Comment by baurmatt** [comment]
@francesco2013 You're welcome! :) But be warned, restarting the Puppetserver might solve this issue now but it (or something similar) will showed up again and again. You need to implement the puppet generate types command at some point to ensure your types aren't poising other environments.

**Comment by francesco2013** [comment]
@baurmatt I still did not try the command. We deploy the puppet code using r10k as I written before as user puppet on the puppet server, but I see that user does not have the puppet executable in its path. I am now wondering if there is a reason for it. Again I can run the **puppet generate types** as root but would be this fine ? Using a user that is not the one we use for r10k ? I know my questions might sound a bit lame but as I said I am not a Puppet expert and I have inherited this infrastructure setup from my predecessor. I am currently migrating all this mess to Rancher 2 and kubernetes, which is way way better than this mess.

**Comment by baurmatt** [comment]
> We deploy the puppet code using r10k as I written before as user puppet on the puppet server, but I see that user does not have the puppet executable in its path. I am now wondering if there is a reason for it. 

The reasons is, that Puppet gets deployed into /opt/puppetlabs/*. The `puppet-agent` package deploys `/etc/profile.d/puppet-agent.sh` with the following content:

```
# Add /opt/puppetlabs/bin to the path for sh compatible users

if ! echo $PATH | grep -q /opt/puppetlabs/bin ; then
  export PATH=$PATH:/opt/puppetlabs/bin
fi
```

Just ensure that this is sourced when you run a command as user `puppet` (e.g. by running an interactive shell) or set it manually. Usually I just hard code the path.

> Again I can run the puppet generate types as root but would be this fine ? Using a user that is not the one we use for r10k would this work as well without side effects ? 

Probably easier if you run it as the same user you do r10k deployments with.

> I am currently migrating all this mess to Rancher 2 and kubernetes, which I like and know much much more than Puppet.

Good luck with that ;)

**Comment by francesco2013** [comment]
> > We deploy the puppet code using r10k as I written before as user puppet on the puppet server, but I see that user does not have the puppet executable in its path. I am now wondering if there is a reason for it.
> 
> The reasons is, that Puppet gets deployed into /opt/puppetlabs/*. The `puppet-agent` package deploys `/etc/profile.d/puppet-agent.sh` with the following content:
> 
> ```
> # Add /opt/puppetlabs/bin to the path for sh compatible users
> 
> if ! echo $PATH | grep -q /opt/puppetlabs/bin ; then
>   export PATH=$PATH:/opt/puppetlabs/bin
> fi
> ```
> Just ensure that this is sourced when you run a command as user `puppet` (e.g. by running an interactive shell) or set it manually. Usually I just hard code the path.
> 
> > Again I can run the puppet generate types as root but would be this fine ? Using a user that is not the one we use for r10k would this work as well without side effects ?
> 
> Probably easier if you run it as the same user you do r10k deployments with.
> 
> > I am currently migrating all this mess to Rancher 2 and kubernetes, which I like and know much much more than Puppet.
> 
> Good luck with that ;)

I am a bit in troubles @baurmatt. I have restarted the puppet server and now the puppet agent throws a new error: 

root@XXXXXXXXXXX:~# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Duplicate declaration: Package[sudo] is already declared in file /etc/puppetlabs/code/environments/production/modules/packages/manifests/init.pp:58; cannot redeclare at /etc/puppetlabs/code/environments/production/modules/sudo/manifests/package.pp:77 at /etc/puppetlabs/code/environments/production/modules/sudo/manifests/package.pp:77:9 on node XXXXXXXXXXXXXXXXX
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Why is it doing this now ? I dont understand what is going on. I did not change a single comma in the puppet server configuration why is it failing like that all of a sudden ? I would need your help once again man. It is rather urgent.

**Comment by francesco2013** [comment]
> @francesco2013 Sorry, you need a proper support channel, a Github issue is definitely not the place for such things. Please come to the Puppet community [slack channel](https://slack.puppet.com/), there might be people around who can help you.

Thank you for this. I will try to ask there. I dont really get what is going on. First the refresh issue of out the blue, then I restarted the server and now this one instead of the previous error. It is totally not logic a complete nonsense which scares me quite a lot
