### ISSUE TITLE
Fails to apply manifest for zabbix-agent 3.0

### ISSUE THREAD

**Issue by RipperSK** [voxpupuli/puppet-zabbix#590]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppetserver                   5.3.6-1stretch
- Ruby: n/a
- Distribution: Debian 9.6
- Module version: puppet-zabbix (v6.7.0)

## How to reproduce (e.g Puppet code you use)
Try the following manifest:

<pre>
node backuper {
  # Install and manage zabbix agent
  class { 'zabbix::agent':
    zabbix_version       => '3.0',
    manage_repo          => true,
    zabbix_package_state => 'present',
    server => '195.98.7.20',
  }
}
</pre>

## What are you seeing
<pre>
root@backuper:~# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for backuper.localdomain
Info: Applying configuration version '1548949212'
Error: Found 1 dependency cycle:
(Apt_key[zabbix-A1848F5] => Apt::Source[zabbix] => Apt::Setting[list-zabbix] => File[/etc/apt/sources.list.d/zabbix.list] => Apt::Setting[list-zabbix] => Apt::Source[zabbix] => Package[dirmngr] => Apt::Key[zabbix-A1848F5] => Apt_key[zabbix-A1848F5])\nTry the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
Error: Failed to apply catalog: One or more resource dependency cycles detected in graph
</pre>

## What behaviour did you expect instead
something like this:
<pre>
root@master:/etc/puppetlabs/code/environments/production/manifests# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for master.localdomain
Info: Applying configuration version '1548950028'
Info: blabla I'm doing something useful and not crashing or complaining
Notice: Applied catalog in 1.78 seconds
</pre>

## Output log
<pre>
root@backuper:~# telnet puppet 8140
Trying 10.11.1.22...
Connected to puppet.
Escape character is '^]'.
^]
telnet> Connection closed.
root@backuper:~# grep -i err /var/log/puppetlabs/*/*
(ok)
2019-01-31 16:37:58,300 INFO  [qtp730443973-16994] [puppetserver] Puppet Compiled catalog for backuper.localdomain in environment production in 1.08 seconds

root@master:/etc/puppetlabs/code/environments/production/manifests# puppet parser validate backuper.pp  -v
(ok)
</pre>

## Any additional information you'd like to impart

I really taught that this was simple

**Comment by bastelfreak** [comment]
Hi @RipperSK, which version of the puppetlabs-apt module do you use? An outdated version?

**Comment by RipperSK** [comment]
Hi Tim,

I was using ├── puppetlabs-apt (v4.2.0)

but since you suggested to upgrade it - I did. Don't get me wrong - I tried
upgrading all the modules before submitting the issue but I ended up with :

Error: Could not upgrade module 'puppetlabs-stdlib' (v4.25.1 -> latest)
  There are 3 newer versions
    No combination of dependency upgrades would satisfy all dependencies

so I just gave up at that point.

Please close the issue since upgrade of apt module to v4.5.1 solved the
problem.

št 31. 1. 2019 o 18:40 Tim Meusel <notifications@github.com> napísal(a):

**Comment by RipperSK** [comment]
And I forgot to thank you :) so thanks for the help man :)

št 31. 1. 2019 o 19:11 Roman Spiak <spiak.roman@gmail.com> napísal(a):

**Comment by bastelfreak** [comment]
I recommend upgrading modules in a test env from time to time to the latest version. Often they work, you just need to ignore the versions in the metadata.json.
