### ISSUE TITLE
Zabbix 4.2 Support

### ISSUE THREAD

**Issue by andreaconsadoriw** [voxpupuli/puppet-zabbix#621]
Any chance to have zabbix 4.2 support?

**Comment by danoe** [comment]
Did you have any problems with the update? I ran it with version 4.2 set and it seems fine so far. `zabbix::zabbix_version: '4.2'`

**Comment by andreaconsadoriw** [comment]
I see is not supported in release notes and I imagine cannot fix the new proxy variables

Andrea Consadori

Head of Front End Team

Mission Critical Infrastructure & Security Expert



WhySecurity Srl

Via del Carmine 1 - Novara

P.IVA IT03404340543



T: +39 0321 1856303

C: +39 3457020228



________________________________
