### ISSUE TITLE
server_logtype should be optional

### ISSUE THREAD

**Issue by trenta** [voxpupuli/puppet-zabbix#655]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.12.0
- Ruby:
- Distribution: Ubuntu 18.04
- Module version: 8.0.0

Currently server_logtype is set by the module with no user option available.  I'd like to set it to file rather than system.

**Comment by baurmatt** [comment]
Hey @trenta,

thanks for opening this issue! :) I see that the parameter `server_logtype` can be configured at the `zabbix::server` class and you can set it to `file`.

https://github.com/voxpupuli/puppet-zabbix/blob/master/manifests/server.pp#L313

What exactly are you missing?

**Comment by trenta** [comment]
So that parameter is taken from this if statement https://github.com/voxpupuli/puppet-zabbix/blob/master/manifests/params.pp#L283

So if the systemd fact returns true then server_logtype is set to system and can't be set by the user.

**Comment by baurmatt** [comment]
That‘s agent_logtype your‘re linking to. Do you mean agent_logtype or server_logtype?

**Comment by trenta** [comment]
Sorry yes https://github.com/voxpupuli/puppet-zabbix/blob/dce7c924109473866f88e316740627e670f6e237/manifests/params.pp#L178.

All over the place this morning :)

**Comment by baurmatt** [comment]
No worries, just wanted to be sure! :)

server_logtype can be configured like this:

```puppet
class { "zabbix::server":
  server_logtype => "file",
}
```

**Comment by trenta** [comment]
Thanks for your help.  Can't believe I missed that.  For the server I'd still be configuring things in the zabbix class.

**Comment by trenta** [comment]
Yeah to just to confirm if you want to use the zabbix class for a single server setup you can't alter this value so I'd have to change to the following explicit setup so I can set that value?

zabbix::web
zabbix::server
zabbix::database
