### ISSUE TITLE
Remove dependency on concat

### ISSUE THREAD

**Issue by CallieNCI** [voxpupuli/puppet-zabbix#658]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.4.0
- Ruby: 
- Distribution:
- Module version: 8.0.0

## How to reproduce (e.g Puppet code you use)

Seen when building an environment using `librarian-puppet` where other modules have a dependency on `puppetlabs/concat` version < 3.0 (in our case the ceph module). The zabbix module want >= 4.1.0

## What are you seeing

Conflicting dependencies around the concat module.

## What behaviour did you expect instead

No Conflict

## Any additional information you'd like to impart

`puppetlabs/concat` is not even a soft dependency for the zabbix module, as only the zabbix modules own dependencies use it. Setting a fact should not be enough reason to have a module dependency (`concat_basedir`).

I think the CEPH module makes as much use of `puppetlabs/concat` as zabbix (ie only it's dependencies use concat).

**Comment by alexjfisher** [comment]
I think you're right, so I'll fix it here.  You may want to open a PR over at https://github.com/openstack/puppet-ceph too.
