### ISSUE TITLE
zabbix::repo should be in setup stage

### ISSUE THREAD

**Issue by xhejtman** [voxpupuli/puppet-zabbix#661]
Class zabbix::repo should be marked to be in setup stage (String $stage = 'setup') otherwise one can get dependency cycle:
(Apt_key[zabbix-A1848F5] => Apt::Source[zabbix] => Apt::Setting[list-zabbix] => File[/etc/apt/sources.list.d/zabbix.list] => Class[Apt::Update] => Exec[apt_update] => Class[Apt::Update] => Stage[setup] => Stage[main] => Class[Zabbix::Repo] => Apt::Source[zabbix])\nTry the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
Error: Failed to apply catalog: One or more resource dependency cycles detected in graph

apt module version 7.0.1

**Comment by baurmatt** [comment]
Hey @xhejtman,

thank you for opening this issue. The apt module documentation clearly states:

> This module is not designed to be split across run stages.
https://github.com/puppetlabs/puppetlabs-apt#limitations
