### ISSUE TITLE
Add Support for Zabbix 5.0

### ISSUE THREAD

**Issue by broadaxe** [voxpupuli/puppet-zabbix#689]
The current version of this module does not support Zabbix 5.0. I know this Zabbix version just got released a couple of days ago, but it would be awesome if/when it is supported. I understand this would take time.
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Latest
- Ruby: Latest with Puppet
- Distribution: CentOS 7
- Module version: Latest

## How to reproduce (e.g Puppet code you use)
Use the current version of these Puppet library to deploy a Zabbix 5.0 server.
## What are you seeing
Some of the packages have been renamed, so it fails to install the old names. In the end, the web based UI for Zabbix is broken.

## What behaviour did you expect instead
I would guess I was to optimistic, I expected to have a working Zabbix server.

**Comment by VibroAxe** [comment]
I would also be keen to see this

**Comment by msnellen** [comment]
I'm also very interested in this as we are currently managing only our Zabbix-agent and would like to migrate to Zabbix 5 in the near future. Would be great if we could use this module to handle the whole thing.

**Comment by aclarkee** [comment]
I believe the main blocker here will be that the ZabbixAPI rubygem only officially supports up to 4.2, and hasn't had any update since [November 2019](https://github.com/express42/zabbixapi)

I wonder where that leaves this module, since it relies heavily on this rubygem.. Either branching off and maintaining a new version of the gem, or talking to the API directly?..

**Comment by jameskirsop** [comment]
At this point, I'm probably going to have to abandon using this module because of the need to move to 5.0 rapidly.

I'm not using the features of this module that require the ZabbixAPI rubygem - and if this is a roadblock to getting 5.0 support, I'd be all for removing support for automatically adding hosts with agents via the API.

**Comment by aclarkee** [comment]
I've actually been doing some testing with zabbix 5.0 - the zabbixapi gem works fine, just warns. 

I'll submit a pull request a bit later, but my usecase is very specific, so not everything is tested. Someone else will have to step up and contribute code to get their usecases working :)

**Comment by jameskirsop** [comment]
@aclarkee Do you have a branch for your changes that I can take a look at and test with (and possibly contribute to)?

**Comment by aredoff** [comment]
We really need zabbix_agent2 support!
Please add new agent support to your wonderful module.

**Comment by aclarkee** [comment]
@jameskirsop Sorry for the late reply, got sidetracked with other priorities. I've just submitted a couple of pull requests with my modifications.

I manage the repo & webserver config outside of this module, so have zabbix::web::manage_repo & zabbix::web::manage_vhost set to false in heira.

**Comment by LarsErikP** [comment]
For what it's worth, I'll "+1" whis. Would love to see Zabbix 5 support, as we're planning to deploy Zabbix in our environment. Would be nice to be able to use the latest version :-)

**Comment by igalic** [comment]
is anyone here able to provide a patch for 5.x support?
is anyone's company here willing to "sponsor" a patch?
(that is, give you the time to work on this)

**Comment by jameskirsop** [comment]
@bastelfreak, could we release/tag the updated version of the module so the 5.0 improvements can be deployed??

**Comment by pkaroluk** [comment]
You can take latest PHP using SCL module so it doesn't seem difficult to implement
``` 
  scl::collection {
    [
      'httpd24',
      'rh-php73',
    ]:
    ensure => present,
    enable => true,
    before => Class['apache'],
  }

  Package {
    [
      'httpd24-mod_ssl',
      'rh-php73-php-mysqlnd',
      'rh-php73-php-gd',
      'rh-php73-php-bcmath',
      'rh-php73-php-mbstring',
      'rh-php73-php-xml',
      'rh-php73-php-json',
      'rh-php73-php-ldap',
    ]:
    ensure => present,
    before => Class['apache'],
  }

  class { '::apache::version':
    scl_httpd_version => '2.4',
    scl_php_version => '7.3',
  }
  -> class { '::apache::mod::prefork':
    startservers => '8';
  }
  -> class { '::apache::mod::php': }
```
(*) I haven't tested it yet with 5.0 version
