### ISSUE TITLE
Allow for configuration of 5.0's zabbix.conf.php SAML settings

### ISSUE THREAD

**Issue by jameskirsop** [voxpupuli/puppet-zabbix#693]
5.0 introduced some new settings that are managed via `zabbix.conf.php` including those for SAML authentication. On a CentOS 7 installation this file is located in `/etc/zabbix/web`.

These would be added to the `zabbix::web` class.

Particular configuration settings to manage:
```
$SSO['SP_KEY'] = '<path to the SP private key file>';
$SSO['SP_CERT'] = '<path to the SP cert file>';
$SSO['IDP_CERT'] = '<path to the IDP cert file>';
$SSO['SETTINGS']
```

Reference: https://www.zabbix.com/documentation/current/manual/web_interface/frontend_sections/administration/authentication#saml_authentication

**Comment by anthonysomerset** [comment]
there is also a DB config value relating to the DB in the 5.0 upgrade 

https://www.zabbix.com/documentation/current/manual/installation/upgrade_notes_500 - Enabling extended range of numeric (float) values
