### ISSUE TITLE
zbx_group vs zbx_groups in Readme

### ISSUE THREAD

**Issue by aberends** [voxpupuli/puppet-zabbix#717]
## What are you seeing
In the README.md file the parameter zbx_group is mentioned. In the code this parameter is deprecated in favor of zbx_groups. But in the README.md only zbx_group is mentioned.

## What behaviour did you expect instead
I would expect to see in the README.md that zbx_group is deprecated and mentioning of the newer way, i.e. zbx_groups.

## Any additional information you'd like to impart
Also related to issue #445.

**Comment by igalic** [comment]
@aberends, do you think you could provide us with a patch here?
