### ISSUE TITLE
Ensure future compatibility with systemd

### ISSUE THREAD

**Issue by 0none** [voxpupuli/puppet-zabbix#740]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Any
- Ruby: Any
- Distribution: Any, using Systemd
- Module version: 8.0.0, master

## Any additional information you'd like to impart
This is really just a heads-up.
In a recent commit on the puppet module "systemd" which is a dependency for this module, the code that creates the resource `Exec[systemctl-daemon-reload]` is dropped.
This causes any node that has the zabbix::agent class to fail with the error message listed below.

Commit in question:
https://github.com/camptocamp/puppet-systemd/commit/97dd16fa32886b5b0f77a6f38a4953d4c1511c0e

## How to reproduce (e.g Puppet code you use)
Check out master branch of camptocamp/systemd, deploy node with `class { 'zabbix::agent' ...` configured.

## What are you seeing
Failure to compile catalog, since the resource `Exec[systemctl-daemon-reload]` is missing.

## What behaviour did you expect instead
The dependency being met.

## Output log
`2021-02-23T14:18:26.858+01:00 ERROR [qtp1804988349-2269] [puppetserver] Puppet Could not find resource 'Exec[systemctl-daemon-reload]' for relationship from 'File[/etc/systemd/system/zabbix-agent.service]' on node ((redacted))`

**Comment by tuxmea** [comment]
There are two possible solutions:
1. remove the notify on the exec daemon-reload and drop support for puppet < 6.1
2. add the exec resource and keep compatibility with puppet < 6.1

Which solution do we prefer?
@bastelfreak @0none

**Comment by root-expert** [comment]
It's being addressed here #742 . Not ready though

**Comment by rwaffen** [comment]
it looks ready now, ran into the same problem and tested master from this module and it is working again.
