### ISSUE TITLE
Zabbix:agent error with module puppet-systemd > 3.3.0

### ISSUE THREAD

**Issue by lduriez** [voxpupuli/puppet-zabbix#799]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.24.0
- Distribution: Amazon Linux 2 & CentOS 7
- Module version: 9.1.0

## How to reproduce (e.g Puppet code you use)
puppet-zabbix 9.1.0 et puppet-systemd > 3.3.0

## What are you seeing
When apply zabbix::agent classes I had the following error :
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Class[Systemd]: expects a value for parameter 'accounting' (file: /etc/puppetlabs/code/environments/production/modules/zabbix/manifests/startup.pp, line: 40, column: 5) (file: /etc/puppetlabs/code/environments/production/modules/zabbix/manifests/agent.pp, line: 439)
```

When downgraded to puppet-systemd 3.3.0 the error disappear.

In [puppet-systemd version 3.4.0](https://forge.puppet.com/modules/puppet/systemd/changelog#v340-2021-09-03) they adding an enhancement about "accounting" I think that's the failure point.

**Comment by root-expert** [comment]
@lduriez master branch of this module should be fixing this issue.
