### ISSUE TITLE
startup_script fails for windows

### ISSUE THREAD

**Issue by logicminds** [voxpupuli/puppet-zabbix#817]
This bug is caused due to a case sensitivity issue with the service name for windows.  On windows the service name is capitalized while everything else it is lowercase.   This causes the service to not start because the fail function is executed.  A case insensitive comparison will fix this issue. 

https://github.com/voxpupuli/puppet-zabbix/blob/master/manifests/startup.pp#L32

https://github.com/voxpupuli/puppet-zabbix/blob/master/manifests/params.pp#L103

## What are you seeing
The catalog fails: `we currently only support a title that contains agent or server`

## What behaviour did you expect instead
The catalog to complete sucessfully

**Comment by smortex** [comment]
Puppet string comparison is not case sensitive, but repexp are. One can make them case insensitive [but the syntax is not that readable](https://puppet.com/docs/puppet/7/lang_data_regexp.html#lang_data_regexp-regex-options), maybe better [downcase](https://puppet.com/docs/puppet/7/function.html#downcase) the service name :wink:
