### ISSUE TITLE
Proxy schema file incorrect for Zabbix 6

### ISSUE THREAD

**Issue by Damianv99** [voxpupuli/puppet-zabbix#838]
## Affected Puppet, Ruby, OS and module versions/distributions

- Module version: 9.2.0

## How to reproduce (e.g Puppet code you use)
Installing a proxy with either Mysql or Postgresql

## What are you seeing
both Zabbix::Database::mysql.pp and Zabbix::Database::postgresql.pp are looking for the schema file schema.sql.gz which no longer exists.
The proxy schema uses a file called proxy.sql which is no longer a Gzip compressed file either.

https://git.zabbix.com/projects/WEB/repos/documentation/browse/en/manual/installation/install_from_packages/debian_ubuntu.md?at=refs%2Fheads%2Frelease%2F6.0

## What behaviour did you expect instead
Correct schema file to be used and imported into database

## Output log
Error: 'cd /usr/share/doc/zabbix-sql-scripts/postgresql && if [ -f schema.sql.gz ]; then gunzip -f schema.sql.gz ; fi && psql -h 'localhost' -U 'zabbix-proxy' -d 'zabbix_proxy' -f schema.sql && touch /etc/zabbix/.schema.done' returned 2 instead of one of [0]
Error: /Stage[main]/Zabbix::Database::Postgresql/Exec[zabbix_proxy_create.sql]/returns: change from 'notrun' to ['0'] failed: 'cd /usr/share/doc/zabbix-sql-scripts/postgresql && if [ -f schema.sql.gz ]; then gunzip -f schema.sql.gz ; fi && psql -h 'localhost' -U 'zabbix-proxy' -d 'zabbix_proxy' -f schema.sql && touch /etc/zabbix/.schema.done' returned 2 instead of one of [0] (corrective)

**Comment by xchotard-talentsoft** [comment]
Same issue here, looks like the files have been moved:
```
# find / -name "proxy.sql" -print
/usr/share/zabbix-sql-scripts/mysql/proxy.sql
/usr/share/zabbix-sql-scripts/sqlite3/proxy.sql
/usr/share/zabbix-sql-scripts/postgresql/proxy.sql
```
I suspect this is related to 6.2.3 because I successfully deployed zabbix proxies in 6.2.2.
