### ISSUE TITLE
Outdated tag 9.2

### ISSUE THREAD

**Issue by Eliesmbr** [voxpupuli/puppet-zabbix#919]
Hello guys!
We have been using your module version 9.2 for a very long time. It is now two years old and in the meantime we have made some updates to our puppet environment, which is slowly becoming incompatible with version 9.2 (apache updated to 12.02 which is not compatible with module version 9.2). Is it planned to push a new tag with the updates of the last two years in the near future? 

Thanks

**Comment by NeatNerdPrime** [comment]
Bumping issue for interest.

curent workaround in Puppetfile would be to use the commit SHA instead of tag. but this is ... urgh... 

Make Tagging Useful Again!

**Comment by Valantin** [comment]
Fixed by #934
