### ISSUE TITLE
zabbix-agent-systemd.init.erb

### ISSUE THREAD

**Issue by KIvanov-1984** [voxpupuli/puppet-zabbix#962]
Hello, you have an error in this file for zabbix-agent2

ExecStart=/usr/sbin/zabbix_agentd in file

ExecStart=/usr/sbin/zabbix_agent2 systemd file for zabbix-agent2

**Comment by Valantin** [comment]
as mentioned here #951 and documented in README and REFERENCE you need to set manage_startup_script to false

**Comment by KIvanov-1984** [comment]
Это не будет работать, так как для запуска Zabbix Agent 2 используется бинарник /usr/sbin/zabbix_agent 2, а для Zabbix Agent /usr/sbin/zabbix_agentd, в файле же шаблона для systemd написано, слейдующее прямым текстом без переменных:
`# THIS FILE IS MANAGED BY PUPPET
[Unit]
Description=Zabbix Agent
After=network.target

[Service]
<% if @service_type %>Type=<%= @service_type %><% end %>
Restart=on-failure
<% if @pidfile %>PIDFile=<%= @pidfile %><% end %>
KillMode=control-group
**ExecStart=/usr/sbin/zabbix_agentd** <%= @additional_service_params %> -c <%= @agent_configfile_path %>
<% if @zabbix_user %>User=<%= @zabbix_user %><% end %>
RestartSec=10s

[Install]
WantedBy=multi-user.target`
Thus Zabbix Agent 2 will not start

**Comment by Valantin** [comment]
ok, probably I assume something not know by other,
but in this section of the readme https://github.com/voxpupuli/puppet-zabbix/blob/master/README.md#usage-zabbix-agent2 as reported the minimal code to run agent2
if you not use the minimal code provided to use agent2, agent2 not run properly.

I'm working to a future release to make manage_startup_script false as default to prevent this misanderstanding.
